runtime: python39
instance_class: F2

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  SECRET_KEY: "your-secret-key-here"
  DATABASE_URL: "sqlite:///erpsystem.db"
  
handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
  
entrypoint: gunicorn -b :$PORT app:app
